#: kivy 2.1.0
#: import Settings kivy.uix.settings
#: import ShadowLabel ui.util.shadow
#: import ShadowButton ui.util.shadow
#: import ShadowImage ui.util.shadow
#: import Clock kivy.clock.Clock


BoxLayout:

    MyVideo:
        id: video

        BottomBar:
            id: bottom_bar

        TopBar:
            id: top_bar

        LeftBar:
            id: left_bar

        RightBar:
            id: right_bar

    RightPanel:
        id: right_panel
