#: kivy 2.1.0
#: import Settings kivy.uix.settings
#: import MyVideo ui.video.video
#: import Joystick kivy-joystick.Joystick

# ============ TEMPLATES ============

# ============ MAIN UI ============
FloatLayout:

    # === BACKGROUND LIVE VIDEO STREAM ===
    MyVideo:
        id: video

    # === MAIN CENTER CONTROLS ===
    GridLayout:
        cols: 3
        size_hint: (1, .3 * float(app.config.get('ui', 'scaling')))
        pos_hint: {'x': 0, 'y': 0}
        opacity: 0.5 * float(app.config.get('ui', 'opacity'))
        RelativeLayout:
            Joystick:
                id: joystick_left
            Image:
                id: keyboard_w
                source: 'assets/keyboard/W_Key_Dark.png'
                pos_hint: {'x': 0.5 - 0.2/2, 'y': 1.0 - 0.2}
                size_hint: (0.2, 0.2)
                allow_stretch: True
            Image:
                id: keyboard_s
                source: 'assets/keyboard/S_Key_Dark.png'
                pos_hint: {'x': 0.5 - 0.2/2, 'y': 0.0}
                size_hint: (0.2, 0.2)
                allow_stretch: True
            Image:
                id: keyboard_a
                source: 'assets/keyboard/A_Key_Dark.png'
                pos_hint: {'x': 0.0, 'y': 0.5 - 0.2/2}
                size_hint: (0.2, 0.2)
                allow_stretch: True
            Image:
                id: keyboard_d
                source: 'assets/keyboard/D_Key_Dark.png'
                pos_hint: {'x': 1.0 - 0.2, 'y': 0.5 - 0.2/2}
                size_hint: (0.2, 0.2)
                allow_stretch: True
        BoxLayout:
            size_hint: (2 / float(app.config.get('ui', 'scaling')), .1)
            orientation: 'vertical'
            BoxLayout: # Just a spacer to move the buttons to the bottom
                size_hint: (None, 4)
            RelativeLayout:
                Button:
                    id: takeoff_land_button
                    text: 'Takeoff'
                Image:
                    id: keyboard_space
                    source: 'assets/keyboard/Space_Key_Dark.png'
                    pos_hint: {'x': 0.4, 'y': 0.5}
                    allow_stretch: True
                Image:
                    id: gamepad_y
                    source: 'assets/controller/XboxSeriesX_Y.png'
                    pos_hint: {'x': 0.5, 'y': 0.5}
                    allow_stretch: True
        RelativeLayout:
            Joystick:
                id: joystick_left
            Image:
                id: keyboard_up
                source: 'assets/keyboard/Arrow_Up_Key_Dark.png'
                pos_hint: {'x': 0.5 - 0.2/2, 'y': 1.0 - 0.2}
                size_hint: (0.2, 0.2)
                allow_stretch: True
            Image:
                id: keyboard_down
                source: 'assets/keyboard/Arrow_Down_Key_Dark.png'
                pos_hint: {'x': 0.5 - 0.2/2, 'y': 0.0}
                size_hint: (0.2, 0.2)
                allow_stretch: True
            Image:
                id: keyboard_left
                source: 'assets/keyboard/Arrow_Left_Key_Dark.png'
                pos_hint: {'x': 0.0, 'y': 0.5 - 0.2/2}
                size_hint: (0.2, 0.2)
                allow_stretch: True
            Image:
                id: keyboard_right
                source: 'assets/keyboard/Arrow_Right_Key_Dark.png'
                pos_hint: {'x': 1.0 - 0.2, 'y': 0.5 - 0.2/2}
                size_hint: (0.2, 0.2)
                allow_stretch: True


    # === TOP-RIGHT SETTINGS/STATUS ===
    BoxLayout:
        id: top_right_panel
        orientation: 'vertical'
        size_hint: (.1, .3 * float(app.config.get('ui', 'scaling')))
        pos_hint: {'x': .9, 'y': 1 - .3 * float(app.config.get('ui', 'scaling'))}
        opacity: 0.25 * float(app.config.get('ui', 'opacity'))
        Button:
            text: 'Settings'
            on_release: app.open_settings()
        BoxLayout: # Just a spacer to move the buttons to the top
            size_hint: (None, 4)
