#: kivy 2.1.0
#: import Settings kivy.uix.settings
#: import MyVideo ui.video.video
#: import Joystick kivy-joystick.Joystick
#: import ShadowLabel ui.util.shadow

# ============ TEMPLATES ============

# ============ MAIN UI ============
FloatLayout:

    # === BACKGROUND LIVE VIDEO STREAM ===
    MyVideo:
        id: video

    # === MAIN CENTER CONTROLS ===
    GridLayout:
        cols: 3
        size_hint: (1, .4 * float(app.config.get('ui', 'scaling')))
        pos_hint: {'x': 0, 'y': 0}
        opacity: 0.5 * float(app.config.get('ui', 'opacity'))
        RelativeLayout:
            size_hint: (None, None)
            size: (.4 * root.height * float(app.config.get('ui', 'scaling')), .4 * root.height * float(app.config.get('ui', 'scaling')))
            Joystick:
                id: joystick_left
            Image:
                id: keyboard_w
                source: 'assets/keyboard/W_Key_Dark.png'
                pos_hint: {'x': 0.5 - 0.2/2, 'y': 1.0 - 0.2}
                size_hint: (0.2, 0.2)
                allow_stretch: True
            Image:
                id: keyboard_s
                source: 'assets/keyboard/S_Key_Dark.png'
                pos_hint: {'x': 0.5 - 0.2/2, 'y': 0.0}
                size_hint: (0.2, 0.2)
                allow_stretch: True
            Image:
                id: keyboard_a
                source: 'assets/keyboard/A_Key_Dark.png'
                pos_hint: {'x': 0.0, 'y': 0.5 - 0.2/2}
                size_hint: (0.2, 0.2)
                allow_stretch: True
            Image:
                id: keyboard_d
                source: 'assets/keyboard/D_Key_Dark.png'
                pos_hint: {'x': 1.0 - 0.2, 'y': 0.5 - 0.2/2}
                size_hint: (0.2, 0.2)
                allow_stretch: True
        BoxLayout:
            orientation: 'vertical'
            BoxLayout: # Just a spacer to move the buttons to the bottom
                size_hint: (None, 4)
            RelativeLayout:
                ShadowButton:
                    id: takeoff_land_button
                    text: 'Takeoff'
                    pos_hint:
                        { 'x': 0.5 - self.width / 2 / max(self.parent.width, 1), \
                        'y': 0.5 - self.height / 2 / max(self.parent.height, 1) }
                    size_hint: None, 1
                Image:
                    id: keyboard_space
                    source: 'assets/keyboard/Space_Key_Dark.png'
                    pos_hint: {'center_x': 0.5 - root.ids.takeoff_land_button.width / 2 / max(1, self.parent.width), 'center_y': 0.9}
                    size_hint: 55 / self.parent.height, 55 / self.parent.height
                    allow_stretch: True
                Image:
                    id: gamepad_y
                    source: 'assets/controller/XboxSeriesX_Y.png'
                    pos_hint: {'center_x': 0.5 + root.ids.takeoff_land_button.width / 2 / max(1, self.parent.width), 'center_y': 0.9}
                    size_hint: 55 / self.parent.height, 55 / self.parent.height
                    allow_stretch: True
        RelativeLayout:
            size_hint: (None, None)
            size: (.4 * root.height * float(app.config.get('ui', 'scaling')), .4 * root.height * float(app.config.get('ui', 'scaling')))
            Joystick:
                id: joystick_left
            Image:
                id: keyboard_up
                source: 'assets/keyboard/Arrow_Up_Key_Dark.png'
                pos_hint: {'x': 0.5 - 0.2/2, 'y': 1.0 - 0.2}
                size_hint: (0.2, 0.2)
                allow_stretch: True
            Image:
                id: keyboard_down
                source: 'assets/keyboard/Arrow_Down_Key_Dark.png'
                pos_hint: {'x': 0.5 - 0.2/2, 'y': 0.0}
                size_hint: (0.2, 0.2)
                allow_stretch: True
            Image:
                id: keyboard_left
                source: 'assets/keyboard/Arrow_Left_Key_Dark.png'
                pos_hint: {'x': 0.0, 'y': 0.5 - 0.2/2}
                size_hint: (0.2, 0.2)
                allow_stretch: True
            Image:
                id: keyboard_right
                source: 'assets/keyboard/Arrow_Right_Key_Dark.png'
                pos_hint: {'x': 1.0 - 0.2, 'y': 0.5 - 0.2/2}
                size_hint: (0.2, 0.2)
                allow_stretch: True


    # === TOP-LEFT STATUS ===
    BoxLayout:
        id: top_left_panel
        orientation: 'vertical'
        size_hint: (.05 * float(app.config.get('ui', 'scaling')), .3 * float(app.config.get('ui', 'scaling')))
        pos_hint: {'x': 0, 'y': 1 - self.size_hint[1]}
        opacity: 0.5 * float(app.config.get('ui', 'opacity'))
        Image:
            source: 'assets/other/battery.png'
            allow_stretch: True
            ShadowLabel:
                id: battery_label
                text: '??%'  # TODO: Tooltips for most UI elements!
                # TODO: Red for low!
                pos: self.parent.pos
                size: self.parent.size
                font_size: self.parent.height * 0.5
        FloatLayout:
            Image:
                source: 'assets/other/thermometer.png'
                pos: (self.parent.pos[0] - self.size[0]/4, self.parent.pos[1])
                allow_stretch: True
                ShadowLabel:
                    id: temperature_label
                    text: '??ºC'
                    # TODO: Red for high!
                    pos: (self.parent.pos[0] + self.size[0]/2, self.parent.pos[1])
                    size: self.parent.size
                    font_size: self.parent.height * 0.5
        BoxLayout: # Just a spacer to move the buttons to the top
            size_hint: (None, 5)

    # === TOP-RIGHT SETTINGS ===
    BoxLayout:
        id: top_right_panel
        orientation: 'vertical'
        size_hint: (.04 * float(app.config.get('ui', 'scaling')), .3 * float(app.config.get('ui', 'scaling')))
        pos_hint: {'x': 1 - self.size_hint[0], 'y': 1 - self.size_hint[1]}
        opacity: 0.25 * float(app.config.get('ui', 'opacity'))
        ShadowButton:
            on_release: app.open_settings()
            Image:
                source: 'assets/other/settings.png' # TODO: Easier to see icons (shadows)
                pos: self.parent.pos
                size: self.parent.size
                allow_stretch: True
            Image:
                id: keyboard_o
                source: 'assets/keyboard/O_Key_Dark.png'
                pos: (self.parent.pos[0] - self.parent.size[0] + 5, self.parent.pos[1])
                size: self.parent.size
                allow_stretch: True
        ShadowButton:
            on_release: app.dispatch('on_drone_photo_request')
            Image:
                source: 'assets/other/camera.png'
                pos: self.parent.pos
                size: self.parent.size
                allow_stretch: True
            Image:
                id: keyboard_p
                source: 'assets/keyboard/P_Key_Dark.png'
                pos: (self.parent.pos[0] - self.parent.size[0] + 5, self.parent.pos[1])
                size: self.parent.size
                allow_stretch: True
        BoxLayout: # Just a spacer to move the buttons to the top
            size_hint: (None, 3)
