#: kivy 2.1.0
#: import MyJoystick ui.util.joystick
#: import * ui.util.shadow

<BottomBar>:  # Assumes that the parent is a FloatLayout (or similar, e.g. no layout)
    cols: 3
    pos: self.parent.pos
    size: self.parent.width, self.parent.height * 0.4 * app.ui_scale
    opacity: 0.5 * app.ui_opacity

    RelativeLayout:
        size_hint: (None, None)
        size: [min(self.parent.height, self.parent.width*0.33)] * 2
        MyJoystick:
            id: joystick_left
            on_pad: Clock.schedule_once(lambda _: app.action_joysticks(self.pad_x, self.pad_y, None, None), 0)
        Image:
            source: 'assets/keyboard/W_Key_Dark.png'
            pos_hint: {'x': 0.5 - 0.2/2, 'y': 1.0 - 0.2}
            size_hint: (0.2, 0.2)
        Image:
            source: 'assets/keyboard/S_Key_Dark.png'
            pos_hint: {'x': 0.5 - 0.2/2, 'y': 0.0}
            size_hint: (0.2, 0.2)
        Image:
            source: 'assets/keyboard/A_Key_Dark.png'
            pos_hint: {'x': 0.0, 'y': 0.5 - 0.2/2}
            size_hint: (0.2, 0.2)
        Image:
            source: 'assets/keyboard/D_Key_Dark.png'
            pos_hint: {'x': 1.0 - 0.2, 'y': 0.5 - 0.2/2}
            size_hint: (0.2, 0.2)

    StackLayout: # Stack all controls in the middle automatically!
        orientation: 'lr-bt'
        spacing: 2, 2
        ShadowButton:
            id: takeoff_land_button
            text: 'Takeoff'
            on_press: app.action_takeoff_land()
            color: 1, 1, 0, 1  # Yellow warning color
            size_hint: 1, 0.25
            Image:
                source: 'assets/keyboard/Space_Key_Dark.png'
                pos: self.parent.pos[0] - self.parent.width / 3, self.parent.pos[1]
                size: self.parent.size
            Image:
                source: 'assets/controller/XboxSeriesX_A.png'
                pos: self.parent.pos[0] + self.parent.width * (1/(4/(1.5/2)) + 1/3), self.parent.pos[1] + self.parent.height / (4/(1.5/2))
                size: self.parent.width / 1.5, self.parent.height / 1.5
        ShadowButton:
            id: tracking_button
            text: 'Tracking'
            on_press: app.action_toggle_tracking()
            size_hint: 0.75, 0.25
            Image:
                source: 'assets/controller/XboxSeriesX_Y.png'
                pos: self.parent.pos[0] + self.parent.width * (1/(4/(1.5/2)) + 1/3), self.parent.pos[1] + self.parent.height / (4/(1.5/2))
                size: self.parent.width / 1.5, self.parent.height / 1.5
        Button:
            id: tracking_settings_button
            on_press: app.action_toggle_settings(force=True, menu='Kivy')  # TODO
            size_hint: 0.25, 0.25
            ShadowImage:
                source: 'assets/other/settings.png'
                pos: [self.parent.pos[i] + self.parent.size[i] / 4 for i in range(len(self.parent.size))]
                size: [i / 2 for i in self.parent.size]
        # ShadowButton:
        #     text: 'TO DO'
        #     size_hint: 0.33, 0.25
        # ShadowButton:
        #     text: 'TO DO'
        #     size_hint: 0.34, 0.25
        # ShadowButton:
        #     text: 'TO DO'
        #     size_hint: 0.33, 0.25

    RelativeLayout:
        size_hint: (None, None)
        size: [min(self.parent.height, self.parent.width*0.33)] * 2
        MyJoystick:
            id: joystick_right
            on_pad: Clock.schedule_once(lambda _: app.action_joysticks(None, None, self.pad_x, self.pad_y), 0)
        Image:
            source: 'assets/keyboard/Arrow_Up_Key_Dark.png'
            pos_hint: {'x': 0.5 - 0.2/2, 'y': 1.0 - 0.2}
            size_hint: (0.2, 0.2)
        Image:
            source: 'assets/keyboard/Arrow_Down_Key_Dark.png'
            pos_hint: {'x': 0.5 - 0.2/2, 'y': 0.0}
            size_hint: (0.2, 0.2)
        Image:
            source: 'assets/keyboard/Arrow_Left_Key_Dark.png'
            pos_hint: {'x': 0.0, 'y': 0.5 - 0.2/2}
            size_hint: (0.2, 0.2)
        Image:
            source: 'assets/keyboard/Arrow_Right_Key_Dark.png'
            pos_hint: {'x': 1.0 - 0.2, 'y': 0.5 - 0.2/2}
            size_hint: (0.2, 0.2)
