#: kivy 2.1.0

<TopBar>:  # Assumes that the parent is a FloatLayout (or similar, e.g. no layout)
    orientation: 'horizontal'
    pos: self.parent.pos[0], self.parent.pos[1] + self.parent.height - self.height
    size: self.parent.width, self.parent.height * 0.05 * app.ui_scale
    opacity: 0.5 * app.ui_opacity

    canvas:
        Color:
            rgba: 0.1, 0.1, 0.1, 1
        Rectangle:
            pos: self.pos
            size: self.size