name: Dependabot Auto Merge
on:
  pull_request:

permissions: write-all
  
jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
