name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write # Required to upload artifacts to releases (and pushing the version update)

jobs:
  update-version:
    name: Update version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master' # HACK: Should be the tag, but we are making a push to master
      - name: Auto-update __version__ and move the release tag
        run: |
          export VERSION="${GITHUB_REF##*/}"
          sed -E -i "s/^__version__ = '.*'$/__version__ = '${VERSION:1}'/" src/main.py  # e.g. v0.0.1 -> version = "0.0.1"
          git config --global user.email "yeicor@users.noreply.github.com"
          git config --global user.name "Yeicor"
          if git commit -am "Update __version__ to ${VERSION:1} (automatic)"; then
            git push
            # Move the tag to the new commit
            git tag -f -a "$VERSION" -m "$VERSION"
            git push -f --tags # Force push the tag to GitHub
            # The tag move will NOT trigger a new workflow
          else
            echo "No change to the version (did you repeat a release tag??)"
            exit 1
          fi

  build-mobile:
    name: Builds for mobile
    runs-on: '${{ matrix.os }}'
    needs:
      - update-version
    strategy:
      fail-fast: false
      matrix:
        include:
          # Android
          - os: ubuntu-latest
            command: buildozer android debug  # TODO: Build for multiple architectures
          # iOS
          - os: macos-latest
            command: buildozer ios debug
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install system dependencies (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          export PATH=$PATH:~/.local/bin/

      - name: Install system dependencies (macos)
        if: matrix.os == 'macos-latest'
        run: |
          brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer autoconf automake
          python3 -m pip install --user --upgrade kivy-ios

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install python dependencies
        run: pip3 install --user -r requirements.txt

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: ${{ matrix.command }}

      - name: Publish the build
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          token: ${{ secrets.GITHUB_TOKEN }}


  build-desktop:
    name: Builds for desktop
    runs-on: '${{ matrix.os }}'
    needs:
      - update-version
    strategy:
      fail-fast: false
      matrix:
        include: # TODO: Release different feature combinations (app-only, server-only and both)
          # Linux x86_64
          - os: ubuntu-latest
            deps: |
              sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
              libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0 gstreamer1.0-plugins-base \
              gstreamer1.0-plugins-good upx
          # Mac OS x86_64
          - os: macos-latest
            deps: ""
          # Windows x86_64
          - os: windows-latest
            deps: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install system dependencies
        if: matrix.deps != ''
        run: ${{ matrix.deps }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: Install python dependencies
        run: pip3 install --user -r requirements.txt

      - name: Build a single executable with PyInstaller
        run: python -m PyInstaller desktop.spec

      - name: Publish the build
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}